### ISSUE TITLE
One of the alien image is not loading

### ISSUE THREAD

**Issue by mohan-murali** [mohan-murali/onet_ten#3]
It seems like one of the alien image is not loading for some reason. Kindly check on this.

Screenshot for refrence

<img width="421" alt="Screenshot 2022-12-15 at 11 21 46" src="https://user-images.githubusercontent.com/26025710/207846913-6e97ed4a-1f08-4946-8134-c9fc39cd6e14.png">

**Comment by Keerthiprasanthr** [comment]
Resolved
